version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - network
    # volumes:
    #   - db:/data/db
  apolloserver:
    depends_on:
      - mongodb
    build:
      context: ./server
      dockerfile: Dockerfile.apollo
    volumes:
      - vol:/synapse/src
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - 6868:6868
    environment:
      # - DB_HOST=mongodb
      - PRODUCTION=false
    stdin_open: true
    tty: true
    networks:
      - network
    # volumes:
    #   - node_modules:/server/node_modules
  guiserver:
    depends_on:
      - mongodb
    build:
      context: ./server
      dockerfile: Dockerfile.gui
    volumes:
      - vol:/synapse/src
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - 4005:4005
    environment:
      - DB_HOST=mongodb
      - PRODUCTION=false
    stdin_open: true
    tty: true
    networks:
      - network
networks:
  network:
volumes:
  vol:
#   node_modules:
