version: '3.8'

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    # ports:
    #   - 7017:27017
    # volumes:
    #   - db:/data/db
  apolloserver:
    image: patelaneesh4/apolloserver
    depends_on:
      - mongodb
    build:
      context: server
      dockerfile: Dockerfile.apollo
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - 6868:6868
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - PRODUCTION=true
    stdin_open: true
    tty: true
    # volumes:
    #   - node_modules:/server/node_modules
  guiserver:
    image: patelaneesh4/guiserver
    depends_on:
      - mongodb
    build:
      context: server
      dockerfile: Dockerfile.gui
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - 4005:4005
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - PRODUCTION=true
    stdin_open: true
    tty: true

# volumes:
#   db:
#   node_modules: