sources:
  - name: test_authors
    handler:
      openapi:
        source: ./openapi-schemas/test_authors-schema.yaml
  - name: test_books
    handler:
      openapi:
        source: ./openapi-schemas/test_books-schema.yaml
