sources:
  - name: AuthorService
    handler:
      openapi:
        source: ./openapi-schemas/AuthorService-schema.yaml
  - name: JsonTestService
    handler:
      jsonSchema:
        baseUrl: www.example.com
        operations:
          - type: Query
            field: users
            path: /users
            method: GET
            responseSchema: ./json-schemas/JsonTestService-schemas/users.json
  - name: MongooseTestService
    handler:
      mongoose:
        connectionString: www.example.com
        models:
          - name: Dogs
            path: ./models/Dogs
