sources:
  - name: TestService
    handler:
      mongoose:
        connectionString: www.example.com
        models:
          - name: People
            path: /path/models
  - name: JSONSchemaService
    handler:
      jsonSchema:
        baseUrl: test
        operations:
          - type: Query
            field: users
            path: /users
            method: GET
            responseSchema: ./json-schemas/users.json
